add CFP-2023-10-24
cilium/design-cfps pull request #20
Opened 2024-02-26 12:57 UTC by hacktivist123

This PR adds [CFP-2023-10-24: multicast support in Cilium](https://docs.google.com/document/d/14ekQd1MoKK9_NX0ru9rrhIHSfOyk_WkKQF7-aTLt3I0/edit?usp=sharing) to the CFP list

2024-02-26 17:38 UTC, joestringer commented
cc @ldelossa does this match the latest implementation details?

2024-02-26 17:52 UTC, joestringer requested changes

2024-02-26 17:52 UTC, joestringer commented on cilium/CFP-2023-10-24-multicast-support-in-cilium.md
> +# CFP-2023-10-24: multicast support in cilium
https://github.com/cilium/cilium/issues/28750
```suggestion
# CFP-28750: multicast support in cilium
```

2024-02-26 17:52 UTC, joestringer commented on cilium/CFP-2023-10-24-multicast-support-in-cilium.md
> +**SIG: SIG-AGENT**
```suggestion
**SIG: SIG-Datapath**
```

2024-07-09 13:27 UTC, xmulligan commented
@lliu0947 do you mind if I close this since multicast has been implemented separately from this CFP in Cilium?

2024-08-02 19:59 UTC, joestringer commented
As much as I would like to have the design of multicast documented, at this point that's up to the contributors involved in that effort to do the write-up. I don't think it's helping the situation if the three people interacting on this PR aren't involved in the proposal.

2024-08-02 19:59 UTC, closed without merging